version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    container_name: neolab-front
    environment:
      # Переменные окружения можно задать здесь или через .env файл
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-https://neolab-backend.aydlioh.ru/}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
